export { default as ArrowRightIcon } from "./ArrowRightIcon"
export { default as OurGoalIcon } from "./OurGoalIcon"
export { default as WhatWeDoIcon } from "./WhatWeDoIcon"
export { default as WhatWeUseIcon } from "./WhatWeUseIcon"
export { default as ReactLogoSmall } from "./ReactLogoSmall"
export { default as ReactLogoLarge } from "./ReactLogoLarge"
