"use client"


import { useRouter } from "next/navigation";

export default function Head() {
//   const router = useRouter();

//   function path() {
//     if (router. === "/") {
//       return "Home";
//     } else {
//       return router.asPath;
//     }
//   }

  return (
    <>
      <title>ReactJS ATX | {} </title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <style>@layer fonts, resets, base, layout, page, theme;</style>
    </>
  );
}
